sudo: required
services:
  - docker

before_install:
  - docker build -t douglasthoms/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true douglasthoms/react-test npm test

after_success:
  - docker build -t douglasthoms/multi-client ./client
  - docker build -t douglasthoms/multi-nginx ./nginx
  - docker build -t douglasthoms/multi-server ./server
  - docker build -t douglasthoms/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  -docker push douglasthoms/multi-client
  -docker push douglasthoms/multi-nginx
  -docker push douglasthoms/multi-server
  -docker push douglasthoms/multi-worker
